
import type { Metadata } from "next";
import "./globals.css";
import Nav from './Components/Nav'
import { Alexandria } from 'next/font/google'
import { Analytics } from "@vercel/analytics/react"




const alexandria = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "3amaly Courses",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {


  return (     

    <html  className={alexandria.className}>  
      <body>
        <Nav />
           {children}
           <Analytics />
      </body>
    </html>
  
  );
}
