
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '../Components/Nav'

import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import { useTranslations } from 'next-intl'



// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "3amaly Courses",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale:string}
}) {
    // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (     
 
    <html lang={locale}>  
      <body>
       <NextIntlClientProvider messages={messages}>
        <Nav />
           {children}
       </NextIntlClientProvider>
      </body>
    </html>

  );
}
