
import type { Metadata } from "next";
import "./globals.css";
import Nav from '../Components/Nav'
import { Alexandria } from 'next/font/google'
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import { useTranslations } from 'next-intl'
import { Analytics } from "@vercel/analytics/react"




const alexandria = Alexandria({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "3amaly Courses",
  description: "Generated by create next app",
};
const locales = ['en', 'ar'];

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale:string}
}) {
    // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();


  return (     

    <html lang={locale} className={alexandria.className}>  
   
      <body>
       <NextIntlClientProvider messages={messages}>
        <Nav />
           {children}
           <Analytics />
       </NextIntlClientProvider>
      </body>
    </html>
  
  );
}
